platform :ios, '8.0'
use_frameworks!

target 'shangzhuocai' do
  pod 'SwiftyJSON','2.3.2'
  pod 'Alamofire','3.2.0'
  pod 'Toast','3.0'
  pod 'SDWebImage','3.7.5'
  pod 'MBProgressHUD','0.9.2'
  pod 'MJRefresh','3.1.0'
  pod 'SVProgressHUD','2.0-beta8'
end
